// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace IdentityService.FunctionalTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 用户登录认证Feature : object, global::Xunit.IClassFixture<用户登录认证Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("zh-CN"), "Features", "用户登录认证", "  作为身份认证服务\r\n  我希望验证用户凭证并签发访问令牌\r\n  以便合法用户能够访问受保护的资源", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Authentication.feature"
#line hidden
        
        public 用户登录认证Feature(用户登录认证Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
  #line hidden
#line 9
    await testRunner.GivenAsync("功能测试环境已就绪", ((string)(null)), ((global::Reqnroll.Table)(null)), "假如");
#line hidden
#line 10
    await testRunner.AndAsync("数据库已初始化种子数据", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Authentication.feature.ndjson", 9);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="管理员使用正确账号密码登录成功")]
        [global::Xunit.TraitAttribute("FeatureTitle", "用户登录认证")]
        [global::Xunit.TraitAttribute("Description", "管理员使用正确账号密码登录成功")]
        public async global::System.Threading.Tasks.Task 管理员使用正确账号密码登录成功()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("管理员使用正确账号密码登录成功", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"Admin@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 14
    await testRunner.ThenAsync("登录响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 15
    await testRunner.AndAsync("返回访问令牌", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 16
    await testRunner.AndAsync("返回刷新令牌", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 17
    await testRunner.AndAsync("登录用户学工号为 \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 18
    await testRunner.AndAsync("登录用户角色包含 \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="使用错误密码登录被拒绝")]
        [global::Xunit.TraitAttribute("FeatureTitle", "用户登录认证")]
        [global::Xunit.TraitAttribute("Description", "使用错误密码登录被拒绝")]
        public async global::System.Threading.Tasks.Task 使用错误密码登录被拒绝()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用错误密码登录被拒绝", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"wrong-password\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 22
    await testRunner.ThenAsync("登录响应失败", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 23
    await testRunner.AndAsync("错误码为 \"AUTH-1001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="使用不存在的账号登录被拒绝")]
        [global::Xunit.TraitAttribute("FeatureTitle", "用户登录认证")]
        [global::Xunit.TraitAttribute("Description", "使用不存在的账号登录被拒绝")]
        public async global::System.Threading.Tasks.Task 使用不存在的账号登录被拒绝()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用不存在的账号登录被拒绝", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.WhenAsync("用户 \"ghost-user\" 使用密码 \"Test@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 27
    await testRunner.ThenAsync("登录响应失败", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 28
    await testRunner.AndAsync("错误码为 \"AUTH-1001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="缺少必填参数导致校验失败")]
        [global::Xunit.TraitAttribute("FeatureTitle", "用户登录认证")]
        [global::Xunit.TraitAttribute("Description", "缺少必填参数导致校验失败")]
        public async global::System.Threading.Tasks.Task 缺少必填参数导致校验失败()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("缺少必填参数导致校验失败", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.WhenAsync("发起空登录请求", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 32
    await testRunner.ThenAsync("登录响应失败", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 33
    await testRunner.AndAsync("错误码为 \"COMMON-2002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="学生账号使用演示密码登录成功")]
        [global::Xunit.TraitAttribute("FeatureTitle", "用户登录认证")]
        [global::Xunit.TraitAttribute("Description", "学生账号使用演示密码登录成功")]
        public async global::System.Threading.Tasks.Task 学生账号使用演示密码登录成功()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("学生账号使用演示密码登录成功", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.WhenAsync("用户 \"S2026001\" 使用密码 \"Test@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 37
    await testRunner.ThenAsync("登录响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 38
    await testRunner.AndAsync("返回访问令牌", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 39
    await testRunner.AndAsync("登录用户学工号为 \"S2026001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="刷新令牌可以换取新的令牌对")]
        [global::Xunit.TraitAttribute("FeatureTitle", "用户登录认证")]
        [global::Xunit.TraitAttribute("Description", "刷新令牌可以换取新的令牌对")]
        public async global::System.Threading.Tasks.Task 刷新令牌可以换取新的令牌对()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("刷新令牌可以换取新的令牌对", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 41
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"Admin@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 43
    await testRunner.AndAsync("使用当前刷新令牌发起刷新", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 44
    await testRunner.ThenAsync("刷新响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 45
    await testRunner.AndAsync("返回新的访问令牌", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 46
    await testRunner.AndAsync("旧的刷新令牌已失效", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="使用无效的刷新令牌被拒绝")]
        [global::Xunit.TraitAttribute("FeatureTitle", "用户登录认证")]
        [global::Xunit.TraitAttribute("Description", "使用无效的刷新令牌被拒绝")]
        public async global::System.Threading.Tasks.Task 使用无效的刷新令牌被拒绝()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用无效的刷新令牌被拒绝", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"Admin@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 50
    await testRunner.AndAsync("使用无效的刷新令牌 \"invalid-refresh-token\" 发起刷新", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 51
    await testRunner.ThenAsync("刷新响应失败", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 52
    await testRunner.AndAsync("错误码为 \"AUTH-1001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 用户登录认证Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 用户登录认证Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
