// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace IdentityService.FunctionalTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 数据权限与角色权限下发Feature : object, global::Xunit.IClassFixture<数据权限与角色权限下发Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("zh-CN"), "Features", "数据权限与角色权限下发", "  作为身份认证服务\r\n  我希望按用户角色计算数据权限范围并下发权限点\r\n  以便业务服务与前端依据数据范围与权限控制访问", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DataScope.feature"
#line hidden
        
        public 数据权限与角色权限下发Feature(数据权限与角色权限下发Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
  #line hidden
#line 9
    await testRunner.GivenAsync("功能测试环境已就绪", ((string)(null)), ((global::Reqnroll.Table)(null)), "假如");
#line hidden
#line 10
    await testRunner.AndAsync("数据库已初始化种子数据", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DataScope.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="系统管理员登录获得全量数据权限")]
        [global::Xunit.TraitAttribute("FeatureTitle", "数据权限与角色权限下发")]
        [global::Xunit.TraitAttribute("Description", "系统管理员登录获得全量数据权限")]
        public async global::System.Threading.Tasks.Task 系统管理员登录获得全量数据权限()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("系统管理员登录获得全量数据权限", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"Admin@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 14
    await testRunner.ThenAsync("登录响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 15
    await testRunner.AndAsync("登录用户数据权限为 \"ALL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 16
    await testRunner.AndAsync("登录用户角色包含 \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="学生登录获得最小数据权限")]
        [global::Xunit.TraitAttribute("FeatureTitle", "数据权限与角色权限下发")]
        [global::Xunit.TraitAttribute("Description", "学生登录获得最小数据权限")]
        public async global::System.Threading.Tasks.Task 学生登录获得最小数据权限()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("学生登录获得最小数据权限", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.WhenAsync("用户 \"S2026001\" 使用密码 \"Test@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 20
    await testRunner.ThenAsync("登录响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 21
    await testRunner.AndAsync("登录用户数据权限为 \"SELF\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 22
    await testRunner.AndAsync("登录用户角色包含 \"student\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="教师登录获得部门班级数据权限")]
        [global::Xunit.TraitAttribute("FeatureTitle", "数据权限与角色权限下发")]
        [global::Xunit.TraitAttribute("Description", "教师登录获得部门班级数据权限")]
        public async global::System.Threading.Tasks.Task 教师登录获得部门班级数据权限()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("教师登录获得部门班级数据权限", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.WhenAsync("用户 \"T1001\" 使用密码 \"Test@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 26
    await testRunner.ThenAsync("登录响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 27
    await testRunner.AndAsync("登录用户数据权限为 \"DEPT\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 28
    await testRunner.AndAsync("登录用户角色包含 \"teacher\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="管理员通过 /me 获取系统管理权限点")]
        [global::Xunit.TraitAttribute("FeatureTitle", "数据权限与角色权限下发")]
        [global::Xunit.TraitAttribute("Description", "管理员通过 /me 获取系统管理权限点")]
        public async global::System.Threading.Tasks.Task 管理员通过Me获取系统管理权限点()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("管理员通过 /me 获取系统管理权限点", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"Admin@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 32
    await testRunner.AndAsync("携带登录访问令牌访问 \"/api/v1/me\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 33
    await testRunner.ThenAsync("响应中的当前用户数据权限为 \"ALL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 34
    await testRunner.AndAsync("响应中的当前用户权限包含 \"sys:user\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 35
    await testRunner.AndAsync("响应中的当前用户权限包含 \"sys:role\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="学生通过 /me 不包含系统管理权限点")]
        [global::Xunit.TraitAttribute("FeatureTitle", "数据权限与角色权限下发")]
        [global::Xunit.TraitAttribute("Description", "学生通过 /me 不包含系统管理权限点")]
        public async global::System.Threading.Tasks.Task 学生通过Me不包含系统管理权限点()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("学生通过 /me 不包含系统管理权限点", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.WhenAsync("用户 \"S2026001\" 使用密码 \"Test@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 39
    await testRunner.AndAsync("携带登录访问令牌访问 \"/api/v1/me\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 40
    await testRunner.ThenAsync("响应中的当前用户数据权限为 \"SELF\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 41
    await testRunner.AndAsync("响应中的当前用户权限不包含 \"sys:user\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="数据权限取用户全部角色中最严格的档位")]
        [global::Xunit.TraitAttribute("FeatureTitle", "数据权限与角色权限下发")]
        [global::Xunit.TraitAttribute("Description", "数据权限取用户全部角色中最严格的档位")]
        public async global::System.Threading.Tasks.Task 数据权限取用户全部角色中最严格的档位()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("数据权限取用户全部角色中最严格的档位", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.WhenAsync("用户 \"T1001\" 使用密码 \"Test@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 45
    await testRunner.ThenAsync("登录响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 46
    await testRunner.AndAsync("登录用户数据权限为 \"DEPT\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 47
    await testRunner.AndAsync("登录用户角色包含 \"head_teacher\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 数据权限与角色权限下发Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 数据权限与角色权限下发Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
