// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace IdentityService.FunctionalTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 接口访问鉴权Feature : object, global::Xunit.IClassFixture<接口访问鉴权Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("zh-CN"), "Features", "接口访问鉴权", "  作为 API 网关\r\n  我希望校验访问令牌并透传用户身份\r\n  以便未授权请求无法访问受保护资源", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Authorization.feature"
#line hidden
        
        public 接口访问鉴权Feature(接口访问鉴权Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
  #line hidden
#line 9
    await testRunner.GivenAsync("功能测试环境已就绪", ((string)(null)), ((global::Reqnroll.Table)(null)), "假如");
#line hidden
#line 10
    await testRunner.AndAsync("数据库已初始化种子数据", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Authorization.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="未携带令牌访问受保护接口返回 401")]
        [global::Xunit.TraitAttribute("FeatureTitle", "接口访问鉴权")]
        [global::Xunit.TraitAttribute("Description", "未携带令牌访问受保护接口返回 401")]
        public async global::System.Threading.Tasks.Task 未携带令牌访问受保护接口返回401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("未携带令牌访问受保护接口返回 401", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.WhenAsync("未携带令牌访问 \"/api/v1/me\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 14
    await testRunner.ThenAsync("响应状态码为 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="携带无效令牌访问受保护接口返回 401")]
        [global::Xunit.TraitAttribute("FeatureTitle", "接口访问鉴权")]
        [global::Xunit.TraitAttribute("Description", "携带无效令牌访问受保护接口返回 401")]
        public async global::System.Threading.Tasks.Task 携带无效令牌访问受保护接口返回401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("携带无效令牌访问受保护接口返回 401", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 17
    await testRunner.WhenAsync("携带令牌 \"not-a-valid-jwt-token\" 访问 \"/api/v1/me\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 18
    await testRunner.ThenAsync("响应状态码为 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="携带有效令牌可以访问当前用户信息")]
        [global::Xunit.TraitAttribute("FeatureTitle", "接口访问鉴权")]
        [global::Xunit.TraitAttribute("Description", "携带有效令牌可以访问当前用户信息")]
        public async global::System.Threading.Tasks.Task 携带有效令牌可以访问当前用户信息()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("携带有效令牌可以访问当前用户信息", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"Admin@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 22
    await testRunner.AndAsync("携带登录访问令牌访问 \"/api/v1/me\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 23
    await testRunner.ThenAsync("响应状态码为 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 24
    await testRunner.AndAsync("响应中的当前用户学工号为 \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 25
    await testRunner.AndAsync("响应中的当前用户角色包含 \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="登出后令牌被拉黑, 再次访问返回 401")]
        [global::Xunit.TraitAttribute("FeatureTitle", "接口访问鉴权")]
        [global::Xunit.TraitAttribute("Description", "登出后令牌被拉黑, 再次访问返回 401")]
        public async global::System.Threading.Tasks.Task 登出后令牌被拉黑再次访问返回401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("登出后令牌被拉黑, 再次访问返回 401", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.WhenAsync("用户 \"admin\" 使用密码 \"Admin@123\" 通过密码模式登录", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 29
    await testRunner.AndAsync("携带登录访问令牌调用登出接口", ((string)(null)), ((global::Reqnroll.Table)(null)), "并且");
#line hidden
#line 30
    await testRunner.ThenAsync("登出响应成功", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
#line 31
    await testRunner.WhenAsync("携带已登出的访问令牌访问 \"/api/v1/me\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 32
    await testRunner.ThenAsync("响应状态码为 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="白名单接口无需令牌即可访问")]
        [global::Xunit.TraitAttribute("FeatureTitle", "接口访问鉴权")]
        [global::Xunit.TraitAttribute("Description", "白名单接口无需令牌即可访问")]
        public async global::System.Threading.Tasks.Task 白名单接口无需令牌即可访问()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("白名单接口无需令牌即可访问", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.WhenAsync("未携带令牌访问 \"/health\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "当");
#line hidden
#line 36
    await testRunner.ThenAsync("响应状态码为 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "那么");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 接口访问鉴权Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 接口访问鉴权Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
